esphome:
  name: waschmaschine
  friendly_name: Waschmaschine
  includes:
    - miele-brain/MotorolaLedDriverSniffer.h
  platformio_options:
    build_flags: -O2
    board_build.f_cpu: 160000000L

esp8266:
  board: d1_mini    

external_components:
  - source: github://Zanooda/miele-novotronic@main
    components: [ miele_novotronic ]

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

text_sensor:
  - platform: template
    name: Time Left
    update_interval: 7d
    id: miele_time
    icon: "mdi:washing-machine"
    
  - platform: template
    name: State
    update_interval: 7d
    id: miele_state
    icon: "mdi:washing-machine"
    
  - platform: miele_novotronic
    id: sniffer
    time_sensor: miele_time
    state_sensor: miele_state

status_led:
  pin:
    number: D4
    inverted: true


